<?php include VIEW . 'header.phtml';

	$action   = $this->getAction();
	$articles = $this->getArticles();
?>
<h1><?php echo $action ?></h1>
<?php
foreach ($articles as $article => $value) {	
	echo $value->getTitle()->getTextContent();
	echo '</br>';
	echo $value->getTextContent()->getTextContent();
	echo '</br>';
	echo $value->getCategory()->getName()->getTextContent();
	echo '</br></br>';
}
?>
<?php include VIEW . 'footer.phtml';?>