<?php include VIEW . 'header.phtml';

	$action  = $this->getAction();
	$article = $this->getArticle();

?>

<h1><?php echo $action ?></h1>

<fieldset>
	<legend>My Article</legend>
		<form action="/administration" method="POST">
		Title:<br>
		<input type="text" name="title" value="<?php echo $article->getTitle() ?>"><br>
		Text:<br>
		<textarea name="text" id="editor">
			<?php echo $article->getTextContent() ?>
		</textarea>
		<input type="hidden" name="id" value="<?php echo $article->getID() ?>">
		<input type="submit" name="update" value="Modify Article">
	</form> 
</fieldset>
<script>
    ClassicEditor
        .create( document.querySelector( '#editor' ) )
        .catch( error => {
            console.error( error );
        } );
</script>
<?php include VIEW . 'footer.phtml';?>