<?php
	$action = $this->getAction();
	$request = $_SERVER['REQUEST_URI'];
	$url = explode('/', $request);
?>

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>My Site</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	<script src="https://cdn.ckeditor.com/ckeditor5/12.0.0/classic/ckeditor.js"></script>
</head>
<body>

	<?php
	if ($url[1] == 'administration'){
		$navBar = $this->showAdminNavBar();
		$navBar->navBar();
	}
	?>



