<?php
	$action = $this->getAction();
?>

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>My Site</title>
	<link href="/style.css" rel="stylesheet" media="all">
</head>
<body>
	<nav>
		<ul>
			<li><a href="/home/index">Site Index</a></li>
			<li><a href="/home/aboutUs">About Us</a></li>
			<li><a href="/article/index">Article Index</a></li>
			<li><a href="/article/newArticle">New Article</a></li>
		</ul>
	</nav>


