language: php
php:
  - '7.2'

dist: trusty

services:
  - docker



addons:
  sonarcloud:
    organization: "tenecort"
    token:
      secure: $SONAR_TOKEN # encrypted value of your token

git:
  depth: false
  
script:
  - php -v
   #- sudo apt-get update
   #- wget https://phar.phpunit.de/phpunit-8.3.phar
   #- chmod +x phpunit-8.3.phar
   #- docker-compose up -d
   #- sleep 15
   #- ./phpunit-8.3.phar --bootstrap tests/init.php tests/. --whitelist=app/. --coverage-clover=coverage-report.clover --log-junit=test-report.xml --debug
   #- sonar-scanner
