language: php
php:
  - '7.2'

dist: trusty

services:
  - docker

addons:
  sonarcloud:
    organization: "tenecort"
    token:
      secure: $SONAR_TOKEN # encrypted value of your token

git:
  depth: false
  
before_script:
  - sudo apt-get update
  - sudo apt-get install apache2 libapache2-mod-fastcgi
  # enable php-fpm
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - sudo sed -i -e "s,www-data,travis,g" /etc/apache2/envvars
  - sudo chown -R travis:travis /var/lib/apache2/fastcgi
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  # configure apache virtual hosts
  - sudo cp -f build/travis-ci-apache /etc/apache2/sites-available/000-default.conf
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/000-default.conf
  - sudo service apache2 restart

script:
   - wget https://phar.phpunit.de/phpunit-8.3.phar
   - chmod +x phpunit-8.3.phar
   - docker-compose up -d
   - sleep 15
   - cd public/
   - nohup php -S localhost:8000 &
   - cd ..
   - ./phpunit-8.3.phar --bootstrap tests/init.php tests/. --whitelist=app/. --coverage-clover=coverage-report.clover --log-junit=test-report.xml --debug
   - sonar-scanner
