language: php
php:
  - '7.2'

dist: trusty

services:
  - docker

env:
  - PHP_ENV=ci PORT=8000

addons:
  sonarcloud:
    organization: "tenecort"
    token:
      secure: $SONAR_TOKEN # encrypted value of your token

git:
  depth: false

before_install:
  - sudo apt-get update
  
script:
   - sudo apt-get update
   - wget https://phar.phpunit.de/phpunit-8.3.phar
   - chmod +x phpunit-8.3.phar
   - docker-compose up -d
   - sleep 10
   #- php -S 127.0.0.1:8080 &
   - ./phpunit-8.3.phar --bootstrap tests/init.php tests/. --whitelist=app/. --coverage-clover=coverage-report.clover --log-junit=test-report.xml --debug
   #- ps -a
   - sonar-scanner
