language: php
php:
  - '7.2'

dist: trusty

addons:
  sonarcloud:
    organization: "tenecort"
    token:
      secure: $SONAR_TOKEN # encrypted value of your token

git:
  depth: false
  
script:
   - wget https://phar.phpunit.de/phpunit-8.3.phar
   - chmod +x phpunit-8.3.phar
   - ./phpunit-8.3.phar --bootstrap tests/init.php tests/. -c phpunit.xml.dist --coverage-clover=coverage-report.clover --log-junit=test-report.xml
   - sonar-scanner
