<?php include VIEW . 'header.phtml';

	$action = $this->getAction();
	$articles = $this->getArticles();

?>

<h1><?php echo $action ?></h1>


<?php //ar_dump($articles);

foreach ($articles as $article => $value) {

	echo('<form action="/article/readArticle/' . $value->getID() . '" method="POST">'
			. $value->getTitle() . $value->getTextContent() . '</a>
			<input type="hidden" name = "articleID" value="' . $value->getID() . '">
			<input type="submit" name = "submit" value="Read Article">
		</form>');
	
}
?>	


<?php include VIEW . 'footer.phtml';?>