<?php include VIEW . 'header.phtml';
	$action = $this->getAction();
	$articles = $this->getArticles();
	$categories = $this->getCategories();
?>

<h1><?php echo $action ?></h1>
<!-- ARTICLE SELECTION -->
<div class="jumbotron">
	<h1 class="display-4">Articles</h1>
	<hr class="my-4">
	<div class="dropdown">
	  <button class="btn btn-dark dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
	    Choose Article
	  </button>
	  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
	  	<?php foreach ($articles as $article => $value) {


	  		echo ('
	  			<form action="/administration/readArticle/' . $value->getID() . '" method="POST">
	  				<input class="dropdown-item" type="submit" name = "submitArticle" value="' . $value->getTitle()->getTextContent() . '">
	  				<input type="hidden" name = "articleID" value="' . $value->getID() . '">
	  			</form>
	  			');
	  	}?>
	  </div>
	</div>
	<hr class="my-4">
	<!-- ARTICLE CREATION -->
	<form action="/administration" method="POST">
  		<div class="form-group">
  			<label for="title">Article Title</label>
  			<input type="text" class="form-control" id="title" aria-describedby="titleHelp" placeholder="Enter article title" name="title">
  		</div>	
  		<div class="form-group">
  			<label for="text">Article Text</label>
  			<input type="text" class="form-control" id="text" aria-describedby="textHelp" placeholder="Enter article text" name="text">
  		</div>


  		<div class="form-group">
			<label for="category">Category select</label>
			<select class="form-control" id="category" name="category">
				<?php foreach ($categories as $category => $value) {
					echo ('<option value="' . $value->getID() . '">' . $value->getName()->getTextContent() . '</option>');
				}?>
			</select>
		</div>


  		<button type="submit" class="btn btn-dark" name ="createArticle" value="Create Article">Create Article</button>	
  	</form>
</div>
<!-- CATEGORY SELECTION -->
<div class="jumbotron">
	<h1 class="display-4">Categories</h1>
	<hr class="my-4">
	<div class="dropdown">
		<button class="btn btn-dark dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
		Choose Categories
		</button>
		<div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
			<?php foreach ($categories as $category => $value) {
			echo ('
				<form action="/administration/readArticle/' . $value->getID() . '" method="POST">
					<input class="dropdown-item" type="submit" name = "submit" value="' . $value->getName()->getTextContent() . '">
	  				<input type="hidden" name = "categoryID" value="' . $value->getID() . '">
				</form>
			');
			}?>
		</div>
	</div>
	<hr class="my-4">
	<!-- CATEGORY CREATION -->
	<form action="/administration" method="POST">
  		<div class="form-group">
  			<label for="title">Category Title</label>
  			<input type="text" class="form-control" id="name" aria-describedby="categoryHelp" placeholder="Enter category name" name="name">
  		</div>
  		<button type="submit" class="btn btn-dark" name ="createCategory" value="Create Category">Create Category</button>	
  	</form>
</div>

<?php include VIEW . 'footer.phtml';?>